# Use Python 3.11 to avoid distutils issues in 3.12
FROM python:3.11-slim

# Set environment vars
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project files
COPY . .

# Run the Django app using gunicorn
CMD ["gunicorn", "Project.wsgi:application", "--bind", "0.0.0.0:8000"]
