FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN python -m venv --copies /opt/venv
RUN . /opt/venv/bin/activate && pip install -r requirements.txt
# Install required system dependencies including build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# Upgrade tools before install
RUN pip install --upgrade pip setuptools wheel && pip install -r requirements.txt



COPY . .

CMD ["gunicorn", "Project.wsgi:application", "--bind", "0.0.0.0:8000"]
