# Generated by Django 5.0.6 on 2024-10-05 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('pricing', models.EmailField(max_length=100)),
                ('comments', models.CharField(max_length=1200)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 5)),
        ),
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 5)),
        ),
    ]
