# Generated by Django 5.0.6 on 2024-10-17 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_bugs_delete_bug_alter_login_date_alter_signup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 17)),
        ),
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 17)),
        ),
    ]
