# Generated by Django 5.0.6 on 2025-02-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_encryptedfile_alter_login_date_alter_signup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryptedfile',
            old_name='key',
            new_name='encrypted_key',
        ),
    ]
