# Generated by Django 5.0.6 on 2025-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_rename_key_encryptedfile_encrypted_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='encrypted_key',
            field=models.CharField(max_length=255),
        ),
    ]
