# Generated by Django 5.0.6 on 2025-02-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_encryptedfile_encrypted_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='destroyed_pixels_file',
            field=models.FileField(blank=True, null=True, upload_to='encrypted_files/'),
        ),
    ]
