# Generated by Django 5.0.6 on 2025-02-18 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_encryptedfile_destroyed_pixels_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='destroyed_pixels_file',
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(upload_to='static/assets/images/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 18)),
        ),
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 18)),
        ),
    ]
