# Generated by Django 5.0.6 on 2025-05-20 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_remove_encryptedfile_destroyed_pixels_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 20)),
        ),
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 20)),
        ),
    ]
