# Generated by Django 5.0.6 on 2025-05-20 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_alter_login_date_alter_signup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='file',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 21)),
        ),
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 21)),
        ),
    ]
