# Generated by Django 5.0.6 on 2025-05-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_encryptedimage_delete_encryptedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/assets/images/')),
                ('filename', models.CharField(max_length=255, null=True)),
                ('encrypted_key', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EncryptedImage',
        ),
    ]
